project:
  type: book

book:
  title: "Apuntes del Modelado en Blender"
  author: "Luis Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - introEditor.qmd
    - objetos.qmd
    - extrusion.qmd
    - comandos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
    toc-title: Contenido
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml



