# Las herramientas en Blender

## Extrusión

Esta herramienta es útil para crear nueva geometría a partir de alguna ya existente. Básicamente, extruir significa estirar una superficie desde su posición inicial.

### Uso de la herramienta

Abriremos Blender con el cubo por defecto y cambiamos al modo Edición (con {{<kbd Tab>}}). Habilitamos la selección por caras y buscamos la herramienta *Extruir región* que se encuentra en la parte izquierda de la Vista. Veremos que si seleccionamos una cara, aparece un círculo con un signo "+" de color amarillo. Pues bien, demos clic en ese signo y arrastremos hacia arriba. Hemos "extraído" otro cubo a partir del original. Otra manera de seleccionar la extrusión es presionar {{<kbd E>}}. Y si deseamos ser más precisos, justo después presionamos la cantidad de metros a extruir (cada cuadro de la rejilla es un metro). Por ejemplo, para extruir una cara lateral la seleccionamos, presionamos {{<kbd E>}} y enseguida {{<kbd 2>}}.

Todas las modificaciones que ya hemos visto pueden realizarse sobre las caras extruidas, podemos moverlas, rotarlas o escalarlas.

Sabiendo eso, ¿cómo podríamos crear una clásica piñata mexicana de seis puntas minimalista?

Volvemos a abrir Blender y cambiamos al modo Edición. Habilitamos la selección por caras y seleccionamos una. La extruimos cuatro metros ({{<kbd E>}} {{<kbd 4>}} {{<kbd Intro>}}) y enseguida la escamos a cero ({{<kbd S>}} {{<kbd 0>}} {{<kbd Intro>}}). Repetimos con cada cara.

## Corte en bucle

Es una característica fundamental que nos permite agregar mayor resolución a nuestro modelo al dejarnos agregarle más bordes.

### Uso de la herramienta

Con un cubo nuevo y en modo Edición, habilitamos la selección por bordes. Enseguida deseleccionamos el cubo y seleccionamos solo un borde. Luego buscamos la herramienta *Cortar bucle* a la izquierda y damos clic sobre el borde elegido (podemos guiarnos por una línea naranja que atraviesa el modelo). O seleccionamos el borde deseado, presionamos {{<kbd Ctrl+R>}}, damos clic de nuevo sobre el borde y podremos notar que si giramos la rueda del ratón se crearán más o menos "cortes". Si ya decidimos cuántos realizar, podemos dar {{<kbd Intro>}} y ahora cursor cambia a dos flechas: en ese momento podemos  desplazar la posición del corte. Si lo hacemos, damos clic donde deseamos dejar dicho corte. Si no, basta con presionar {{<kbd Intro>}} de nuevo.

De la misma forma que con las caras producto de la extrusión, los bordes que resultan de cortar bucle pueden ser modificados.

Practiquemos. Modelemos una botella "low poly" a partir de un cilindro y una esfera a partir de un cubo.


